### PR TITLE
Make BEE Shields Up

### PR DESCRIPTION
**Pull request by Anarchist2**
i've spent far too long on this
(~sorry becca~)

### CODE REVIEW

**Comment by beccabunny** [comment]
I agree, you've spent far too long on this. Merging immediatly

**Comment by beccabunny** [comment]
You wish

**Comment by Anarchist2** [comment]
smh didn't even look at it all

**Comment by beccabunny** [comment]
I did, that's why I now need to wear glasses

**Comment by Anarchist2** [comment]
i'm leterelly ckrying and shaking rn why could you do this to mbe mbeesdccsa

**Pull request closed without merging**
